### ISSUE TITLE
Upsetting, ablelist, sexist, and other offensive words included in corpus

### ISSUE THREAD

**Issue by catarak** [aceakash/project-name-generator#27]
i was using this project as part of the [p5.js Web Editor](https://github.com/processing/p5.js-web-editor), but ended up removing it as it was possible to generate upsetting and offensive project names (see https://github.com/processing/p5.js-web-editor/issues/1026).

i recommend removing words that in any context could be offensive, or juxtaposed with specific words could be offensive, or words that feel out of context for a project name. some recommendations are, but not limited to: `aboriginal`, `abortive`,  `alcoholic`, `xenophobic`... there are quite a lot of words that i think should be removed. 

thank you!

**Comment by Robbie-Cook** [comment]
Also, can I suggest removing `tightfisted`? I got 'tightfisted-spy' and that was a bit over the line

**Comment by aceakash** [comment]
Thank you, and sorry for the delay in merging the related PR. 
I'll go through the words and keep an eye on further reports.
